-- Tạo bảng Users nếu chưa tồn tại
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- Tạo bảng Orders nếu chưa tồn tại
CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- Tạo bảng OrderProducts nếu chưa tồn tại
CREATE TABLE IF NOT EXISTS "OrderProducts" (
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric NOT NULL,
    CONSTRAINT "PK_OrderProducts" PRIMARY KEY ("OrderId", "ProductId"),
    CONSTRAINT "FK_OrderProducts_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderProducts_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

-- Thêm unique constraint cho email
ALTER TABLE "Users" ADD CONSTRAINT "IX_Users_Email" UNIQUE ("Email");

